// Generated from Rust contracts. Do not hand edit. Runtime semantic validation remains in Node.
export const PROTOCOL_VERSION = 1 as const;
export type Command = ({ "kind": "ListDevices" } | { "kind": "GetCapabilities" } | { "kind": "GetState" } | { "args": { "consent_confirmed": boolean; "display_name": string; "reference_handle": string }; "kind": "CreateVoice" } | { "args": { "voice_id": Id }; "kind": "DeleteVoice" } | { "args": { "source_handle": string; "voice_id": Id }; "kind": "PreviewVoice" } | { "args": { "input_device_id": string; "output_device_id": string; "route": Route; "voice_id": Id }; "kind": "PrepareSession" } | { "args": { "epoch": number; "session_id": Id }; "kind": "StartSession" } | { "args": { "session_id": Id }; "kind": "StopSession" } | { "args": { "epoch": number; "muted": boolean; "session_id": Id }; "kind": "SetMute" } | { "args": { "route": Route }; "kind": "SelectRoute" } | { "args": { "device_id"?: (string | null); "enabled": boolean }; "kind": "SetMonitor" } | { "args": { "db": number }; "kind": "SetGain" } | { "kind": "ListPeers" } | { "kind": "ExportIdentity" } | { "args": { "allow_compute": boolean; "allow_profile_transfer": boolean; "identity": string }; "kind": "ImportPeerIdentity" } | { "args": { "node_id": Id }; "kind": "RevokePeer" } | { "args": { "download_approved": boolean; "manifest_id": string }; "kind": "InstallEngineAssets" } | { "kind": "GetMetrics" } | { "args": { "destination_handle": string }; "kind": "ExportDiagnostics" });
export type DecimalU64 = string;
export type ErrorCode = "INVALID_ARGUMENT" | "UNSUPPORTED_VERSION" | "INVALID_STATE" | "REQUEST_ID_CONFLICT" | "BUSY" | "UNTRUSTED_PEER" | "CERTIFICATE_MISMATCH" | "PERMISSION_DENIED" | "DEVICE_MISSING" | "ENGINE_NOT_READY" | "ENGINE_FAILED" | "INVALID_PROFILE" | "SIZE_LIMIT" | "SESSION_MISMATCH" | "EPOCH_MISMATCH" | "INVALID_MEDIA" | "EXPIRED" | "BACKPRESSURE" | "EPOCH_EXHAUSTED";
export type Id = string;
export type Outcome = ({ "kind": "Ack" } | { "args": { "state": SessionState }; "kind": "State" } | { "args": { "code": ErrorCode; "message": string }; "kind": "Error" });
export type OverflowPolicy = "RejectNewest" | "DropExpiredOldest";
export type PeerMessage = ({ "args": { "node_id": Id }; "kind": "Hello" } | { "kind": "Capabilities" } | { "args": { "model_sha256": Sha256; "profile_sha256": Sha256 }; "kind": "PrepareSession" } | { "args": { "capabilities": PreparedCapabilities; "loaded_profile_sha256": Sha256; "session_tag": DecimalU64 }; "kind": "Prepared" } | { "kind": "RejectBusy" } | { "args": { "profile_sha256": Sha256; "total_bytes": number }; "kind": "AuthorizeProfileTransfer" } | { "args": { "data_base64": string; "offset": number }; "kind": "ProfileChunk" } | { "args": { "profile_sha256": Sha256 }; "kind": "ProfileReady" } | { "kind": "Start" } | { "kind": "Started" } | { "kind": "Mute" } | { "kind": "Muted" } | { "args": { "new_epoch": number }; "kind": "Reset" } | { "kind": "ResetReady" } | { "kind": "Stop" } | { "kind": "Stopped" } | { "kind": "Ping" } | { "kind": "Pong" } | { "kind": "Metrics" } | { "args": { "code": ErrorCode; "message": string }; "kind": "Error" });
export type PeerRequest = { "context"?: (SessionContext | null); "message": PeerMessage; "protocol_version": number; "request_id": Id };
export type PreparedCapabilities = { "backend": string; "capability_test_run_id": string; "chunk_samples": number; "conditioning_schema": string; "device_memory_budget_bytes"?: (DecimalU64 | null); "duration_preserving": boolean; "engine_id": string; "lookahead_samples": number; "model_memory_budget_bytes": DecimalU64; "model_sha256": Sha256; "native_input_rate": number; "native_output_rate": number };
export type QueueBudget = { "capacity_frames": number; "maximum_age_ms": number; "overflow_policy": OverflowPolicy; "target_frames": number };
export type Request = { "command": Command; "protocol_version": number; "request_id": Id };
export type Response = { "outcome": Outcome; "request_id": Id; "state_version": DecimalU64 };
export type Route = ({ "kind": "Local" } | { "args": { "node_id": Id }; "kind": "Remote" });
export type SessionContext = { "epoch": number; "session_id": Id };
export type SessionState = "Idle" | "Preparing" | "Ready" | "Running" | "Stopping" | "Error" | "Blocked" | "Degraded" | "FailedMuted" | "Muted";
export type Sha256 = string;
